[package]
name = "onepack-nuget"
description = "Adaptador NuGet: lectura de paquetes, normalización y protocolo V3."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
onepack-core.workspace = true
quick-xml = "0.42.0"
serde_json = "1.0.151"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[lints]
workspace = true
